import json

def generate():
    data = {}

    pop_t = [
        "What is your most embarrassing moment?", "Who is your secret crush?", "What is your biggest fear?", "What is the most childish thing you still do?", "Have you ever lied to get out of trouble?",
        "What is the worst thing you have ever done?", "Have you ever cheated on a test?", "What is your biggest pet peeve?", "When was the last time you lied?", "What is the most awkward text you’ve ever sent?",
        "Have you ever snooped through someone else's phone?", "What is your worst habit?", "Have you ever peed in a swimming pool?", "What is the weirdest dream you've ever had?", "Have you ever faked an illness to stay home?",
        "Who is your least favorite person in this room?", "What is a secret you’ve never told anyone?", "Have you ever broken something and blamed it on someone else?", "What is the most embarrassing thing you've bought?", "Have you ever practiced kissing in a mirror?",
        "What is the dumbest thing you've ever cried over?", "Have you ever been caught picking your nose?", "What is the grossest thing you've ever eaten?", "Have you ever let someone take the blame for your mistake?", "What is your most embarrassing nickname?",
        "Have you ever eavesdropped on a private conversation?", "What is the longest you've gone without showering?", "Have you ever re-gifted a present?", "What is your weirdest talent?", "Have you ever been rejected by someone you liked?",
        "What is the most trouble you've ever been in?", "Have you ever accidentally sent a message to the wrong person?", "What is your most useless skill?", "Have you ever fallen asleep in public?", "What is the most embarrassing music you listen to?",
        "Have you ever lied about your age?", "What is the most ridiculous rumor you've heard about yourself?", "Have you ever stolen something from a hotel?", "What is the weirdest thing you do when you are alone?", "Have you ever laughed at an inappropriate time?",
        "What is your biggest regret?", "Have you ever had a crush on a teacher?", "What is the worst gift you have ever given someone?", "Have you ever pretended to know a stranger to get out of a situation?", "What is the most embarrassing thing your parents have caught you doing?",
        "Have you ever eaten food off the floor?", "What is the most childish movie you still love?", "Have you ever tried to cut your own hair?", "What is the worst grade you ever got?", "Have you ever pretended to like a gift you hated?",
        "What is the weirdest thing in your room right now?", "Have you ever lied to your parents about where you were?", "What is the most useless thing you’ve ever bought?", "Have you ever forgotten a friend's birthday?", "What is the most awkward date you've ever been on?",
        "Have you ever skipped school?", "What is the weirdest food combination you enjoy?", "Have you ever laughed so hard you cried?", "What is the worst movie you've ever seen?", "Have you ever blamed a fart on someone else?",
        "What is the weirdest text you’ve received?", "Have you ever accidentally liked an old photo on social media?", "What is the most money you’ve ever wasted?", "Have you ever tripped in public and played it off?", "What is the worst haircut you’ve ever had?",
        "Have you ever fallen asleep in a movie theater?", "What is the weirdest app on your phone?", "Have you ever eaten a bug by mistake?", "What is the longest you’ve ever slept?", "Have you ever gotten lost in your own city?",
        "What is the most embarrassing thing you’ve said to a crush?", "Have you ever cried during a commercial?", "What is the weirdest nickname someone has given you?", "Have you ever talked to yourself in the mirror?", "What is the worst joke you know?",
        "Have you ever worn clothes inside out without realizing?", "What is the most ridiculous thing you’ve believed?", "Have you ever pretended to be on the phone to avoid someone?", "What is the most awkward compliment you’ve received?", "Have you ever sent a text to the person you were complaining about?",
        "What is the weirdest thing you’ve searched on Google?", "Have you ever gotten locked out of your house?", "What is the most embarrassing thing you’ve done on a video call?", "Have you ever dropped your phone in the toilet?", "What is the worst piece of advice you’ve ever given?",
        "Have you ever laughed at a joke you didn't understand?", "What is the most embarrassing phase you went through?", "Have you ever lied about watching a movie to fit in?", "What is the weirdest dream you’ve had about someone in this room?", "Have you ever forgotten what you were saying mid-sentence?",
        "What is the most embarrassing thing you’ve worn in public?", "Have you ever waved at someone who wasn't waving at you?", "What is the weirdest thing you’ve done for money?", "Have you ever hidden a snack so you didn't have to share?", "What is the most embarrassing poster you had in your room?",
        "Have you ever lied about your hobbies?", "What is the weirdest fear you had as a kid?", "Have you ever called a teacher 'Mom' or 'Dad'?", "What is the most embarrassing thing you’ve done for a dare?", "Have you ever eaten something out of the trash?",
        "What is the worst thing you’ve ever smelled?", "Have you ever walked into a glass door?", "What is the most embarrassing thing in your search history?", "Have you ever cried because of a book?", "What is the weirdest thing you’ve ever collected?"
    ]

    pop_d = [
        "Do your best dance move for 30 seconds.", "Sing the chorus of your favorite song.", "Let someone post on your social media.", "Do 10 push-ups right now.", "Speak in an accent for the next 3 rounds.",
        "Call a friend and sing Happy Birthday.", "Imitate someone in the room until they guess who you are.", "Do the worm across the floor.", "Let another player draw on your face with a pen.", "Eat a spoonful of a condiment chosen by the group.",
        "Do a plank for a full minute.", "Talk without moving your lips for the next round.", "Let the group look through your search history for 1 minute.", "Try to lick your elbow.", "Do 20 jumping jacks.",
        "Act like a monkey until it's your turn again.", "Let someone style your hair.", "Speak only in whispers for the next 2 rounds.", "Hold an ice cube in your hand until it melts.", "Give your phone to the person on your right to send one text message.",
        "Do your best impression of a baby crying.", "Walk like a crab across the room.", "Try to juggle 3 items chosen by the group.", "Let someone tickle you for 30 seconds.", "Sing everything you say for the next 3 rounds.",
        "Stand on one leg for the next 2 rounds.", "Smell the feet of everyone in the room.", "Make up a rap about the person to your left.", "Try not to blink for 1 minute.", "Let someone feed you a snack while blindfolded.",
        "Talk in a robot voice for the next 3 rounds.", "Act like a dog and fetch an item for someone.", "Do a handstand against the wall.", "Let someone put makeup on you blindfolded.", "Bite into a lemon slice.",
        "Do your best evil laugh.", "Keep your eyes closed until your next turn.", "Pretend to be a news anchor reporting on the game.", "Let someone tickle your feet.", "Try to touch your nose with your tongue.",
        "Do a cartwheel (or try your best).", "Speak with your tongue sticking out for the next round.", "Let the group choose your profile picture for 24 hours.", "Act out a scene from your favorite movie.", "Do 15 squats.",
        "Pretend you are underwater for the next round.", "Let someone give you a wet willy.", "Eat a small piece of paper.", "Wear your socks on your hands for the next 3 rounds.", "Try to spin a book on your finger.",
        "Let someone draw a unibrow on your face.", "Do 10 burpees.", "Sing a nursery rhyme as loudly as you can.", "Let the person to your left do your makeup.", "Walk backwards for the next 3 rounds.",
        "Talk like Shakespeare for the next 2 rounds.", "Let someone pinch your arm.", "Do a dramatic reading of a random text message.", "Hold your breath for as long as you can.", "Let someone tickle your sides for 15 seconds.",
        "Pretend to be a statue for 1 minute.", "Do your best impression of a celebrity.", "Let someone give you a wedgie.", "Eat a spoonful of peanut butter and try to sing.", "Pretend to ride a horse around the room.",
        "Let someone write a word on your forehead.", "Do 5 cartwheels in a row.", "Speak only in questions for the next 3 rounds.", "Let someone pour a cup of cold water on your head.", "Pretend to be a cat and meow at everyone.",
        "Do 20 sit-ups.", "Let someone wrap you in toilet paper like a mummy.", "Pretend to be a mime for the next 2 rounds.", "Let someone draw a mustache on your face.", "Do your best chicken dance.",
        "Let someone crack an egg on your head.", "Pretend to be a robot for the next 3 rounds.", "Let someone put a piece of ice down your back.", "Do your best impression of the person to your right.", "Let someone blindfold you and guess 3 objects by touch.",
        "Pretend to be a dinosaur for the next round.", "Let someone feed you something from the fridge blindfolded.", "Do 15 jumping jacks while singing.", "Let someone tickle your neck.", "Pretend to be a pirate for the next 2 rounds.",
        "Let someone draw a tattoo on your arm.", "Do your best impression of a teacher.", "Let someone put a sticker on your face.", "Pretend to be a baby for the next round.", "Let someone brush your hair.",
        "Do your best impression of a politician.", "Let someone put a hat on you.", "Pretend to be a superhero for the next 2 rounds.", "Let someone put a scarf around your neck.", "Do your best impression of a news reporter.",
        "Let someone put a pair of sunglasses on you.", "Pretend to be a rockstar for the next round.", "Let someone put a necklace on you.", "Do your best impression of a ghost.", "Let someone put a ring on your finger."
    ]

    xtreme_t = [
        "What is the craziest thing you have ever done?", "Have you ever been arrested or almost arrested?", "What is the most dangerous thing you have done?", "Have you ever lied to your best friend?", "What is your darkest secret?",
        "Have you ever stolen something?", "What is the most embarrassing photo of you?", "Have you ever ghosted someone you actually liked?", "What is the worst physical pain you've ever experienced?", "Have you ever been in a physical fight?",
        "What is the most illegal thing you've ever done?", "Have you ever broken someone's heart on purpose?", "What is the biggest lie you've ever kept going?", "Have you ever sneaked out of the house at night?", "What is the most expensive thing you've ruined?",
        "Have you ever lied to the police?", "What is the worst thing you've ever said to someone's face?", "Have you ever betrayed a deep secret?", "What is the biggest mistake of your life?", "Have you ever stalked an ex online?",
        "What is the most manipulative thing you've done?", "Have you ever ruined someone else's relationship?", "What is the most toxic trait you have?", "Have you ever been caught doing something you shouldn't have?", "What is the meanest prank you've ever pulled?",
        "Have you ever lied about your relationship status?", "What is the most risky text you've ever sent?", "Have you ever had a near-death experience?", "What is the worst habit you hide from everyone?", "Have you ever secretly hated a gift someone gave you but wore it anyway?",
        "What is the most desperate thing you've done for attention?", "Have you ever stolen money from a family member?", "What is the darkest thought you've ever had?", "Have you ever sabotaged a coworker or classmate?", "What is the worst thing you've ever done for revenge?",
        "Have you ever trespassed on private property?", "What is the most shocking thing you've witnessed?", "Have you ever lied to get a job or promotion?", "What is the biggest secret you've kept from your parents?", "Have you ever been caught in a massive lie?",
        "What is the most embarrassing thing you've done while drunk?", "Have you ever driven without a license?", "What is the worst financial decision you've ever made?", "Have you ever secretly read someone's diary?", "What is the most dangerous dare you've ever accepted?",
        "Have you ever faked a medical emergency?", "What is the worst rumor you've started about someone?", "Have you ever intentionally started a fight?", "What is the most unforgivable thing you've done?", "Have you ever ran away from home?",
        "What is the most extreme diet you've ever tried?", "Have you ever cheated in a major competition?", "What is the most painful thing you've said to a parent?", "Have you ever stolen a friend's partner?", "What is the most dangerous place you've ever been?",
        "Have you ever lied in court?", "What is the most unethical thing you've ever done for money?", "Have you ever blackmailed someone?", "What is the most reckless decision you've ever made?", "Have you ever vandalized property?",
        "What is the most severe injury you've caused someone else?", "Have you ever forged a signature?", "What is the most terrifying nightmare you've ever had?", "Have you ever lied about having a degree or qualification?", "What is the most extreme fear you have?",
        "Have you ever shoplifted something expensive?", "What is the most scandalous secret you know about someone else?", "Have you ever hacked into someone's account?", "What is the most dangerous stunt you've ever pulled?", "Have you ever participated in an illegal street race?",
        "What is the most violent thought you've ever had?", "Have you ever framed someone for something you did?", "What is the most destructive thing you've ever done in anger?", "Have you ever sneaked into a restricted area?", "What is the most intense pain you've ever felt?",
        "Have you ever lied about a serious illness?", "What is the most extreme measure you've taken to get revenge?", "Have you ever stalked someone in real life?", "What is the most dangerous weapon you've ever handled?", "Have you ever been in a high-speed chase?",
        "What is the most extreme modification you'd make to your body?", "Have you ever cheated a system to get free stuff?", "What is the most terrifying real-life encounter you've had?", "Have you ever lied to get someone fired?", "What is the most extreme phobia you have?",
        "Have you ever been involved in a hit-and-run?", "What is the most illegal thing you've gotten away with?", "Have you ever stolen from an employer?", "What is the most intense adrenaline rush you've ever experienced?", "Have you ever lied to get a loan or credit?",
        "What is the most extreme thing you've done for love?", "Have you ever been a part of a dangerous gang or group?", "What is the most horrifying thing you've ever seen on the internet?", "Have you ever lied about your identity?", "What is the most extreme survival situation you've been in?",
        "Have you ever committed a crime and blamed it on a sibling?", "What is the most extreme act of rebellion you've committed?", "Have you ever been interrogated by the police?", "What is the most dangerous animal you've ever encountered?", "Have you ever lied to escape a speeding ticket?"
    ]

    xtreme_d = [
        "Eat a spoonful of hot sauce.", "Let the group go through your phone for 60 seconds.", "Do a cold water challenge — pour cold water on yourself.", "Text your crush and tell them you miss them.", "Let someone draw on your face with a marker.",
        "Go outside and scream as loud as you can.", "Hold an ice cube in your hand for as long as you can.", "Speak only in questions for the next 2 rounds.", "Call a random number and try to have a 2-minute conversation.", "Eat a raw onion slice.",
        "Let the group post a status on your social media.", "Take a bite out of a stick of butter.", "Drink a mystery mixture created by the group.", "Send a completely random, out-of-context text to your boss or teacher.", "Let someone wax a small patch of hair off your body.",
        "Chew on a piece of garlic.", "Let someone else text your ex.", "Swap clothes with someone in the group.", "Eat a spoonful of mustard.", "Let someone slap you in the face.",
        "Post an embarrassing photo of yourself online right now.", "Let the group look at your hidden photos album.", "Sniff the armpit of the person next to you.", "Do 50 pushups without stopping.", "Call your parents and tell them you got married secretly.",
        "Eat a spoonful of mayonnaise.", "Let someone drop an ice cube down your shirt.", "Give someone your unlocked phone for 2 minutes.", "Drink a raw egg.", "Let someone shave a tiny part of your eyebrow.",
        "Run outside in your socks and run back.", "Bite into a hot pepper.", "Send a voice note to your crush singing a love song.", "Let the group cut a small piece of your hair.", "Eat a pet treat.",
        "Do a handstand and drink water at the same time.", "Let someone write a word on your forehead in permanent marker.", "Lick the bottom of your shoe.", "Call a pizza place and ask for relationship advice.", "Hold a plank until someone else finishes their turn.",
        "Let someone pinch you as hard as they can.", "Eat a spoonful of soy sauce.", "Send an embarrassing selfie to a contact chosen by the group.", "Let the group mix three liquids and you have to drink a sip.", "Walk barefoot outside for 2 minutes.",
        "Let someone draw a unibrow on you.", "Eat a spoonful of coffee grounds.", "Do 10 burpees as fast as you can.", "Let someone spray perfume/cologne directly into your mouth.", "Call a random number and sing happy birthday.",
        "Let someone crack a raw egg on your head.", "Eat a spoonful of salt.", "Drink a shot of vinegar.", "Let someone draw a fake tattoo on your face with a Sharpie.", "Bite into a raw potato.",
        "Let someone dump a cup of flour on your head.", "Eat a spoonful of cinnamon (attempt cautiously).", "Drink a glass of milk with hot sauce in it.", "Let someone wrap your head in duct tape (carefully).", "Eat a spoonful of wasabi.",
        "Let someone spray whipped cream in your face.", "Drink a cup of pickle juice.", "Let someone draw on your teeth with a dry-erase marker.", "Eat a raw mushroom.", "Let someone put a clothespin on your nose for 5 minutes.",
        "Drink a mixture of soda and milk.", "Let someone draw a unibrow on you with a permanent marker.", "Eat a spoonful of plain cocoa powder.", "Let someone pour a glass of water down your pants.", "Drink a shot of lemon juice.",
        "Let someone blindfold you and feed you 3 mystery items.", "Eat a piece of raw pasta.", "Let someone draw a mustache on you with eyeliner.", "Drink a cup of cold coffee with salt.", "Let someone put a piece of tape across your mouth for 2 rounds.",
        "Eat a spoonful of plain baking soda.", "Let someone draw a unibrow on you with lipstick.", "Drink a cup of water with a raw egg mixed in.", "Let someone put a rubber band around your wrist and snap it.", "Eat a piece of dog food (or cat food).",
        "Let someone draw a fake scar on your face.", "Drink a cup of tea with hot sauce.", "Let someone put a drop of hot sauce on your tongue.", "Eat a spoonful of plain flour.", "Let someone draw a unibrow on you with a highlighter.",
        "Drink a cup of water with dirt in it.", "Let someone put a piece of ice in your underwear.", "Eat a spoonful of plain sugar.", "Let someone draw a fake unibrow on you with a pen.", "Drink a cup of water with soap in it.",
        "Let someone put a piece of ice down your pants.", "Eat a spoonful of plain pepper.", "Let someone draw a fake unibrow on you with a pencil.", "Drink a cup of water with vinegar in it.", "Let someone put a piece of ice in your shoe."
    ]

    couple_t = [
        "What was your first impression of your partner?", "What is the most romantic thing you have ever done?", "Have you ever been jealous of your partner? Why?", "What is one thing your partner does that secretly annoys you?", "Describe your perfect date night.",
        "What is the most thoughtful gift you have ever received?", "Have you ever lost feelings for someone?", "What is one thing you wish your partner did more often?", "When did you realize you were in love with your partner?", "What is your favorite memory of us together?",
        "What is a secret you kept from me early in our relationship?", "What is the most attractive physical feature of your partner?", "What is a habit of mine that you’ve learned to love?", "What is your biggest fear regarding our relationship?", "What is the best compliment I’ve ever given you?",
        "Have you ever doubted our relationship?", "What is the most embarrassing thing you did to impress me?", "What is something we don't do anymore that you miss?", "What is your favorite non-physical trait about me?", "What is the hardest thing we’ve overcome as a couple?",
        "What is a fantasy you’ve never shared with me?", "When are you the most proud of me?", "What is something I do that instantly turns you on?", "What is your idea of the perfect kiss?", "What is a boundary you have that you feel I sometimes cross?",
        "What is the most important lesson this relationship has taught you?", "Have you ever considered breaking up during a fight?", "What is something you wish we agreed on more?", "What is your favorite way to receive affection?", "What is something you think I don't understand about you?",
        "What was your favorite date we ever went on?", "What is something you want to achieve together in the next year?", "How has your definition of love changed since we met?", "What is the most surprising thing you’ve learned about me?", "What is a song that always reminds you of me?",
        "What is a place you want to travel to with me?", "What is a hobby you wish we shared?", "What is the best trip we’ve taken together?", "What is a pet name you secretly love being called?", "What is something you think we need to work on?",
        "What is your favorite photo of us?", "What is the most ridiculous argument we’ve ever had?", "What is something I do that always makes you laugh?", "What is a tradition you want to start together?", "What is your favorite memory of us from our first year?",
        "What is something I wore that you absolutely loved?", "What is your favorite way I show you love?", "What is a dream you have for our future?", "What is something you’ve always wanted to ask me but haven’t?", "What is your favorite thing about our intimate life?",
        "What is the most romantic dream you've ever had about me?", "Have you ever secretly checked my phone?", "What is the most attractive outfit I own?", "What is one thing you'd change about our wedding/future wedding?", "What is your favorite part of my personality?",
        "Have you ever lied to me to avoid an argument?", "What is the most thoughtful thing I've ever done for you?", "What is a quirk of mine that you find adorable?", "What is the biggest sacrifice you've made for our relationship?", "What is your favorite thing to do with me on a lazy Sunday?",
        "Have you ever been intimidated by me?", "What is the most spontaneous thing we've ever done?", "What is a secret fear you have about getting older together?", "What is your favorite inside joke we share?", "What is the most meaningful conversation we've ever had?",
        "Have you ever hidden a purchase from me?", "What is the most romantic movie scene that reminds you of us?", "What is a habit of mine you wish you could adopt?", "What is the most difficult challenge we've faced?", "What is your favorite meal I've ever cooked for you?",
        "Have you ever pretended to like a gift I gave you?", "What is the most attractive thing I do without realizing it?", "What is a goal you have for us in the next 5 years?", "What is your favorite physical touch from me?", "What is the most important thing you've learned from me?",
        "Have you ever been embarrassed by something I did in public?", "What is the most romantic song lyrics that make you think of me?", "What is a memory of us that always makes you smile?", "What is the most proud you've ever been of me?", "What is your favorite way to spend an evening together?",
        "Have you ever doubted my love for you?", "What is the most romantic place we've ever been?", "What is a skill you wish I had?", "What is the most meaningful gift you want to give me?", "What is your favorite thing about waking up next to me?",
        "Have you ever felt like you weren't good enough for me?", "What is the most romantic gesture you've always wanted me to make?", "What is a shared interest you love doing with me?", "What is the most important quality you see in me?", "What is your favorite thing about our communication?",
        "Have you ever kept a secret from me to protect my feelings?", "What is the most romantic thing you've ever thought about me?", "What is a tradition of ours you hope we never stop?", "What is the most important way I support you?", "What is your favorite thing about our future together?"
    ]

    couple_d = [
        "Give your partner a 60-second back massage.", "Say three things you love about your partner.", "Let your partner choose your outfit for the next outing.", "Share the last text you sent to your partner.", "Kiss your partner on the forehead.",
        "Cook your partner's favorite meal this week.", "Do a slow dance together for 1 minute.", "Take a cute photo together right now.", "Give your partner a foot rub.", "Stare into your partner's eyes for 60 seconds without blinking.",
        "Recreate your first kiss.", "Write a short love poem for your partner and read it aloud.", "Let your partner blindfold you and feed you a mystery snack.", "Whisper a secret in your partner's ear.", "Give your partner a passionate kiss for 10 seconds.",
        "Let your partner style your hair.", "Exchange phones for the next 2 minutes.", "Serenade your partner with a love song.", "Post a sweet message about your partner on social media.", "Give your partner a piggyback ride across the room.",
        "Let your partner pick a movie for your next date.", "Plan a surprise date for next weekend.", "Hold hands for the next 10 minutes.", "Let your partner draw a temporary tattoo on your arm.", "Do a trust fall with your partner catching you.",
        "Write a love letter to your partner on a napkin.", "Let your partner dress you up in their clothes.", "Make a romantic playlist for your partner.", "Give your partner a neck kiss.", "Trace a word on your partner's back and have them guess it.",
        "Let your partner choose a new nickname for you for the day.", "Re-enact how you first met.", "Let your partner do your makeup.", "Give your partner a long, warm hug.", "Share a piece of food Lady and the Tramp style.",
        "Let your partner tickle you for 30 seconds.", "Leave a sweet voicemail on your partner's phone.", "Let your partner browse your Amazon cart.", "Do a blind taste test created by your partner.", "Let your partner pick your next meal.",
        "Give your partner a compliment every hour for the rest of the day.", "Let your partner control the TV remote for the evening.", "Hold your partner in your arms for 2 minutes.", "Let your partner choose a game for you to play together.", "Give your partner a hand massage.",
        "Let your partner paint one of your nails.", "Share your favorite dream you’ve had about your partner.", "Let your partner write a sweet note and hide it for you to find.", "Give your partner a kiss on the cheek every time they laugh.", "Cuddle with your partner for the next 5 minutes.",
        "Give your partner a gentle kiss on the hand.", "Let your partner blindfold you and guess 3 objects they hand you.", "Write a list of 5 things you appreciate about your partner.", "Let your partner choose the next song to listen to.", "Give your partner a kiss on the nose.",
        "Let your partner draw a heart on your cheek.", "Share a romantic fantasy you have about your partner.", "Let your partner pick a TV show for you to watch.", "Give your partner a hug from behind for 1 minute.", "Let your partner tickle your sides.",
        "Write a sweet text message and send it to your partner right now.", "Let your partner choose a new hairstyle for you.", "Give your partner a kiss on the shoulder.", "Let your partner blindfold you and try to guess what they are drawing on your back.", "Share a romantic memory you have of your partner.",
        "Let your partner pick a snack for you to eat.", "Give your partner a massage for 5 minutes.", "Let your partner choose a new outfit for you to wear.", "Give your partner a kiss on the neck.", "Let your partner blindfold you and guess what they are feeding you.",
        "Share a sweet secret you have about your partner.", "Let your partner pick a movie for you to watch.", "Give your partner a hug for 2 minutes.", "Let your partner choose a new book for you to read.", "Give your partner a kiss on the ear.",
        "Let your partner blindfold you and guess what they are touching on your face.", "Share a romantic quote that reminds you of your partner.", "Let your partner pick a restaurant for you to go to.", "Give your partner a massage for 10 minutes.", "Let your partner choose a new game for you to play.",
        "Give your partner a kiss on the collarbone.", "Let your partner blindfold you and guess what they are spraying in the air.", "Share a sweet thought you have about your partner.", "Let your partner pick a vacation destination for you to go to.", "Give your partner a hug for 5 minutes.",
        "Let your partner choose a new hobby for you to try.", "Give your partner a kiss on the jawline.", "Let your partner blindfold you and guess what they are tracing on your hand.", "Share a romantic poem that reminds you of your partner.", "Let your partner pick a new skill for you to learn.",
        "Give your partner a massage for 15 minutes.", "Let your partner choose a new language for you to learn.", "Give your partner a kiss on the temple.", "Let your partner blindfold you and guess what they are writing on your arm.", "Share a sweet compliment you have for your partner."
    ]

    spicy_t = [
        "What is the most flirtatious thing you have ever done?", "Have you ever had a crush on a friend's partner?", "What is your most attractive quality?", "Who in this room would you go on a date with?", "What is the boldest thing you have ever said to someone you liked?",
        "Have you ever flirted to get something you wanted?", "What is your go-to flirting move?", "What is the most romantic dream you have had?", "What is your biggest turn-on?", "What is your biggest turn-off?",
        "Have you ever sent a spicy text?", "What is your favorite body part on yourself?", "What is your favorite body part on someone else?", "Have you ever kissed someone in public?", "What is the most adventurous place you've ever been intimate?",
        "Have you ever had a friends-with-benefits situation?", "What is a wild fantasy you've always had?", "Have you ever skinny-dipped?", "What is the best kiss you’ve ever had?", "What is the worst date you’ve ever been on?",
        "Have you ever faked a romantic feeling?", "What is a spicy secret you’ve never told your friends?", "Have you ever hooked up with a coworker?", "What is your favorite type of underwear on a partner?", "Have you ever had a crush on someone much older?",
        "What is the most scandalous photo on your phone?", "Have you ever had a one-night stand?", "What is a kink you’ve always wanted to try?", "Have you ever kissed more than one person in a single night?", "What is the most awkward intimate moment you’ve experienced?",
        "Have you ever had romantic feelings for a teacher or boss?", "What is your favorite romantic movie scene?", "Have you ever role-played?", "What is the longest you’ve gone without intimacy?", "Have you ever been caught in a compromising position?",
        "What is a boundary you would never cross in the bedroom?", "Have you ever used a dating app just for fun?", "What is your opinion on public displays of affection?", "Have you ever slept in the same bed as a platonic friend of the opposite gender?", "What is the most sensitive spot on your body?",
        "Have you ever dated two people at the same time?", "What is the most attractive profession to you?", "Have you ever had a crush on a celebrity that you were embarrassed about?", "What is your idea of a perfect romantic evening?", "Have you ever left a hickey on someone?",
        "What is a weird physical trait you find attractive?", "Have you ever been completely naked outdoors?", "What is your favorite way to initiate intimacy?", "Have you ever recorded an intimate moment?", "What is the most passionate thing you've ever done for love?",
        "What is the most seductive outfit you own?", "Have you ever had a crush on a sibling's friend?", "What is the most explicit text you've ever received?", "Have you ever fantasized about someone in this room?", "What is your favorite intimate memory?",
        "Have you ever had a romantic encounter in a car?", "What is the most unusual place you've had a crush on someone?", "Have you ever sent an explicit photo?", "What is your favorite position?", "Have you ever been attracted to a same-sex friend?",
        "What is the most daring thing you've worn in public?", "Have you ever had a secret rendezvous?", "What is the most intense romantic connection you've felt?", "Have you ever been walked in on?", "What is your favorite intimate sound?",
        "Have you ever kissed a stranger?", "What is the most erotic movie you've watched?", "Have you ever had a crush on a fictional character?", "What is your favorite type of foreplay?", "Have you ever had a romantic encounter at a party?",
        "What is the most suggestive song you like?", "Have you ever used a toy?", "What is your favorite time of day for intimacy?", "Have you ever had a romantic encounter in the water?", "What is the most explicit thought you've had today?",
        "Have you ever had a crush on a doctor or nurse?", "What is your favorite intimate scent?", "Have you ever had a romantic encounter in a hotel?", "What is the most intense eye contact you've ever had?", "Have you ever been attracted to someone's voice?",
        "What is the most provocative dance you've done?", "Have you ever had a romantic encounter in the woods?", "What is your favorite intimate taste?", "Have you ever had a crush on a police officer?", "What is the most explicit book you've read?",
        "Have you ever had a romantic encounter on a beach?", "What is your favorite intimate touch?", "Have you ever been attracted to someone's intelligence?", "What is the most suggestive nickname you've had?", "Have you ever had a romantic encounter in a bathroom?",
        "What is your favorite intimate word?", "Have you ever had a crush on a firefighter?", "What is the most explicit joke you know?", "Have you ever had a romantic encounter in a closet?", "What is your favorite intimate fantasy to share?"
    ]

    spicy_d = [
        "Whisper something flirty in the ear of the person to your left.", "Do your best catwalk across the room.", "Give your best smoldering look to the camera for 10 seconds.", "Compliment every person in the room on their appearance.", "Do a dramatic movie-style wink at someone.",
        "Let someone style your hair any way they want.", "Perform your best flirtatious laugh.", "Describe your ideal romantic partner in detail.", "Give someone in the group a sensual neck massage.", "Show the group the spiciest photo on your phone.",
        "Demonstrate how you would kiss someone for the first time on your hand.", "Send a flirty emoji to the 5th person in your contacts.", "Let someone sit on your lap for the next round.", "Read the last flirty text you sent out loud.", "Nibble gently on the earlobe of the person to your right.",
        "Do a sexy dance to a song chosen by the group for 30 seconds.", "Let the group give you a new sensual nickname.", "Kiss the neck of the person next to you.", "Demonstrate your favorite flirting technique.", "Unbutton one button of your shirt (or equivalent).",
        "Let someone trace a shape on your back and guess what it is.", "Give a lap dance to a chair for 30 seconds.", "Bite your lip seductively while staring at someone for 10 seconds.", "Let someone blindfold you and feed you a piece of chocolate.", "Whisper a spicy secret to the person across from you.",
        "Take an item of clothing off.", "Let someone run their fingers through your hair.", "Give someone a hickey on their arm.", "Act out a romantic movie scene with another player.", "Describe a spicy dream you’ve had in detail.",
        "Let someone kiss you anywhere on your face.", "Send a risky text to your crush.", "Let someone outline your lips with their finger.", "Give someone in the room a passionate hug.", "Read an excerpt from a romance novel dramatically.",
        "Let someone tickle your inner thigh for 10 seconds.", "Show off your best assets with a pose.", "Let someone put an ice cube down your back.", "Give a foot massage to someone in the group.", "Let someone kiss your hand sensually.",
        "Breathe heavily into someone's ear.", "Let someone draw a heart on your chest with lipstick.", "Describe your perfect intimate night out.", "Let someone spank you lightly.", "Give someone a sultry look across the room.",
        "Let someone whisper something dirty in your ear.", "Share a piece of candy with someone mouth-to-mouth.", "Let someone tie your hands for the next round.", "Do your best Marilyn Monroe impression.", "Compliment someone's body in the room.",
        "Give someone a gentle bite on the shoulder.", "Let someone blindfold you and guess who is touching your face.", "Do a striptease to one item of clothing.", "Let someone trace a word on your stomach.", "Give someone a sensual kiss on the cheek.",
        "Let someone blindfold you and feed you a strawberry.", "Do a slow, seductive dance.", "Let someone outline your jawline with their finger.", "Give someone a sensual kiss on the forehead.", "Let someone blindfold you and guess who is whispering in your ear.",
        "Do a sexy crawl across the room.", "Let someone trace a word on your inner arm.", "Give someone a sensual kiss on the hand.", "Let someone blindfold you and feed you a piece of fruit.", "Do a seductive hair flip.",
        "Let someone outline your collarbone with their finger.", "Give someone a sensual kiss on the neck.", "Let someone blindfold you and guess who is kissing your hand.", "Do a sexy pose against the wall.", "Let someone trace a word on your thigh.",
        "Give someone a sensual kiss on the earlobe.", "Let someone blindfold you and feed you a piece of ice.", "Do a seductive stretch.", "Let someone outline your lips with a piece of ice.", "Give someone a sensual kiss on the shoulder.",
        "Let someone blindfold you and guess who is hugging you.", "Do a sexy walk across the room.", "Let someone trace a word on your back with a piece of ice.", "Give someone a sensual kiss on the wrist.", "Let someone blindfold you and feed you a piece of candy.",
        "Do a seductive wink.", "Let someone outline your jawline with a piece of ice.", "Give someone a sensual kiss on the palm.", "Let someone blindfold you and guess who is holding your hand.", "Do a sexy pout.",
        "Let someone trace a word on your inner arm with a piece of ice.", "Give someone a sensual kiss on the knuckles.", "Let someone blindfold you and feed you a sip of a drink.", "Do a seductive smile.", "Let someone outline your collarbone with a piece of ice."
    ]

    kids_t = [
        "What is your favorite cartoon character?", "Do you still sleep with a stuffed animal or toy?", "What is your favorite ice cream flavor?", "Have you ever cried during a movie? Which one?", "What superpower would you want?",
        "If you could be any animal, what would you be?", "What is your favorite subject in school?", "Who is your best friend and why?", "What is the funniest face you can make?", "Have you ever hidden a bad grade from your parents?",
        "What is your favorite candy?", "What do you want to be when you grow up?", "Have you ever blamed a sibling for something you did?", "What is the best toy you own?", "What is your favorite video game?",
        "Have you ever stayed up past your bedtime secretly?", "What is your favorite thing to do on weekends?", "Have you ever faked being sick to skip school?", "What is your favorite joke?", "What is the grossest food you’ve ever had to eat?",
        "Have you ever forgotten your homework?", "What is your favorite book?", "Who is your favorite superhero?", "Have you ever sneaked a snack before dinner?", "What is the silliest thing you’re afraid of?",
        "What is your favorite color?", "Have you ever dropped food on the floor and eaten it?", "What is your favorite holiday?", "Who is the funniest person you know?", "Have you ever broken a rule at school?",
        "What is your favorite song to sing?", "What is the coolest dream you've ever had?", "Have you ever forgotten to brush your teeth?", "What is your favorite animal at the zoo?", "What is the best gift you’ve ever received?",
        "Have you ever worn your clothes inside out by accident?", "What is your favorite ride at an amusement park?", "What is the hardest subject in school for you?", "Have you ever fallen off your bike?", "What is your favorite sport to play?",
        "What is the most fun thing you did this summer?", "Have you ever laughed so hard you snorted?", "What is your favorite pizza topping?", "What is the messiest thing you’ve ever done?", "Have you ever accidentally called your teacher 'Mom'?",
        "What is your favorite thing about yourself?", "What is the longest you’ve ever played a video game?", "Have you ever peeked at your Christmas presents early?", "What is your favorite board game?", "Who is your favorite Disney character?",
        "What is your favorite dinosaur?", "Have you ever tried to stay awake all night?", "What is the best prank you've ever played?", "What is your favorite thing to draw?", "Have you ever lost a tooth and swallowed it?",
        "What is your favorite type of cookie?", "Have you ever been afraid of the dark?", "What is the most toys you've ever had in your bed?", "What is your favorite thing to do at recess?", "Have you ever pretended to be a superhero?",
        "What is your favorite animal sound to make?", "Have you ever eaten something off the ground?", "What is the funniest thing a pet has done?", "What is your favorite fairy tale?", "Have you ever tried to dig a hole to China?",
        "What is your favorite thing to build with legos?", "Have you ever been scared of a bug?", "What is the best tree you've ever climbed?", "What is your favorite type of cereal?", "Have you ever pretended to be a dog or cat?",
        "What is your favorite game to play outside?", "Have you ever gotten stuck in a slide?", "What is the funniest face your parents make?", "What is your favorite thing to do in the snow?", "Have you ever tried to catch a butterfly?",
        "What is your favorite thing to do at the beach?", "Have you ever been afraid of a monster under the bed?", "What is the best fort you've ever built?", "What is your favorite type of juice?", "Have you ever pretended to be an astronaut?",
        "What is your favorite game to play inside?", "Have you ever gotten lost in a store?", "What is the funniest joke you've heard recently?", "What is your favorite thing to do in the rain?", "Have you ever tried to catch a frog?",
        "What is your favorite thing to do at a park?", "Have you ever been afraid of a loud noise?", "What is the best drawing you've ever made?", "What is your favorite type of fruit?", "Have you ever pretended to be a pirate?",
        "What is your favorite game to play with friends?", "Have you ever gotten a brain freeze?", "What is the funniest thing you've said?", "What is your favorite thing to do in the summer?", "Have you ever tried to catch a firefly?"
    ]

    kids_d = [
        "Make your best animal sound.", "Hop on one foot for 30 seconds.", "Draw a silly picture and show everyone.", "Do your best superhero pose.", "Sing the ABC song as fast as you can.",
        "Make someone in the room laugh.", "Do 5 jumping jacks.", "Tell a funny joke.", "Act like a robot.", "Try to touch your toes.",
        "Spin around 5 times and try to walk straight.", "Pretend to fly like an airplane around the room.", "Sing a nursery rhyme in a funny voice.", "Try to wiggle your ears.", "Do a silly dance for 15 seconds.",
        "Act like a monkey and scratch your head.", "Try to balance a book on your head.", "Roar like a lion.", "Pretend you are swimming across the room.", "Make a fish face.",
        "Try to lick your own nose.", "Give someone a high five in slow motion.", "Pretend to be a statue and don't move for 20 seconds.", "Walk backward across the room.", "Say a tongue twister 3 times fast.",
        "Act like a dinosaur.", "Try to juggle two pairs of socks.", "Pretend you are invisible.", "Make a funny face and hold it for 10 seconds.", "Pretend to ride a horse.",
        "Sing your favorite song loudly.", "Do the chicken dance.", "Try to pat your head and rub your belly at the same time.", "Act like a cat and meow.", "Pretend you are walking on the moon.",
        "Do your best evil villain laugh.", "Try to sit on a wall (invisible chair) for 15 seconds.", "Pretend to be a ninja.", "Say the alphabet backward as far as you can.", "Act like a baby crying.",
        "Pretend to play a guitar.", "Jump up and down 10 times.", "Pretend to blow up a huge balloon.", "Act like you are freezing cold.", "Pretend to eat the most delicious food ever.",
        "Try to catch an imaginary butterfly.", "Pretend to be a sleeping bear.", "Do a somersault.", "Pretend to be a frog and hop.", "Act like you are driving a race car.",
        "Pretend to be a tree blowing in the wind.", "Do 10 bunny hops.", "Act like a penguin waddling.", "Sing 'Twinkle Twinkle Little Star' in a deep voice.", "Pretend to be a melting snowman.",
        "Walk on your tiptoes across the room.", "Act like a snake slithering.", "Say your name backwards.", "Pretend to be a popping popcorn kernel.", "Do your best impression of a teacher.",
        "Act like a bouncing ball.", "Pretend to brush your teeth in fast motion.", "Sing 'Happy Birthday' underwater (with fingers on lips).", "Pretend to be a waking up in the morning.", "Do a happy dance.",
        "Act like a spider crawling.", "Pretend to eat a very sour lemon.", "Say the days of the week as fast as you can.", "Pretend to be a washing machine.", "Do your best impression of a baby learning to walk.",
        "Act like a bird flying.", "Pretend to drink a very hot cup of cocoa.", "Count to 20 backwards.", "Pretend to be a clock ticking.", "Do your best impression of an old person.",
        "Act like a bear looking for honey.", "Pretend to eat a very spicy pepper.", "Say the months of the year backwards.", "Pretend to be a ringing telephone.", "Do your best impression of a grumpy troll.",
        "Act like a rabbit eating a carrot.", "Pretend to smell a very stinky sock.", "Say your favorite color 5 times fast.", "Pretend to be a train chugging along.", "Do your best impression of a sleeping dog.",
        "Act like a turtle hiding in its shell.", "Pretend to step in a deep puddle.", "Say 'I love pizza' in a robot voice.", "Pretend to be a zooming rocket ship.", "Do your best impression of a happy cat."
    ]

    office_t = [
        "Have you ever pretended to be busy to avoid a task?", "What is the most embarrassing thing that happened to you at work?", "Have you ever taken credit for someone else's idea?", "What is the most unprofessional thing you have done at work?", "Have you ever gossiped about a coworker?",
        "Who in the office do you think is the most overrated?", "Have you ever fallen asleep during a meeting?", "What is your honest opinion about your boss?", "Have you ever lied on your resume?", "What is the biggest mistake you’ve made at work?",
        "Have you ever stolen office supplies?", "What is the most annoying thing a coworker does?", "Have you ever dated a coworker?", "What is the weirdest place you’ve taken a work call?", "Have you ever sent an email to the wrong person?",
        "What is your biggest pet peeve in the office?", "Have you ever ignored a call from your boss?", "What is the longest you’ve taken for a lunch break?", "Have you ever browsed social media during a video call?", "What is the worst job you’ve ever had?",
        "Have you ever cried at work?", "What is a company rule you constantly break?", "Have you ever had a crush on a coworker?", "What is the most ridiculous excuse you’ve used to miss work?", "Have you ever accidentally replied all to a company email?",
        "What is the most boring task you have to do?", "Have you ever exaggerated your skills to get a task done?", "What is the worst presentation you’ve ever given?", "Have you ever snooped on a coworker’s desk?", "What is the most frustrating client you’ve ever dealt with?",
        "Have you ever lied to a client to save face?", "What is your favorite part of the workday?", "Have you ever had a 'work spouse'?", "What is the strangest thing you keep in your desk?", "Have you ever used company time for personal errands?",
        "What is the worst office party you’ve attended?", "Have you ever felt jealous of a coworker's promotion?", "What is a skill you pretend to have but actually don't?", "Have you ever taken a sick day when you were perfectly fine?", "What is the most awkward elevator ride you’ve had at work?",
        "Have you ever forgotten a coworker's name while talking to them?", "What is the weirdest lunch someone has brought to the office?", "Have you ever muted yourself on a call to complain about it?", "What is the most unprofessional outfit you’ve worn to work?", "Have you ever been caught talking to yourself at work?",
        "What is your least favorite corporate buzzword?", "Have you ever regretted taking this job?", "What is the best gossip you’ve ever heard at work?", "Have you ever accidentally insulted a superior?", "What is a secret about your job that outsiders don't know?",
        "What is the most ridiculous request a boss has made?", "Have you ever blamed a mistake on a computer glitch?", "What is the most annoying email sign-off?", "Have you ever left work early without telling anyone?", "What is your favorite office snack?",
        "Have you ever accidentally sent a personal message in a work chat?", "What is the most pointless meeting you've ever attended?", "Have you ever taken home company equipment?", "What is your strategy for avoiding small talk in the breakroom?", "Have you ever forged a signature on a document?",
        "What is the most embarrassing zoom background you've had?", "Have you ever muted a coworker's emails?", "What is the most stressful project you've worked on?", "Have you ever lied about completing a task?", "What is your favorite excuse for being late?",
        "Have you ever accidentally screen-shared something embarrassing?", "What is the most toxic work environment you've been in?", "Have you ever secretly recorded a meeting?", "What is the most passive-aggressive email you've sent?", "Have you ever quit a job dramatically?",
        "What is the most bizarre team-building exercise you've done?", "Have you ever used sick leave for a vacation?", "What is the most inappropriate joke you've heard at work?", "Have you ever fallen asleep at your desk?", "What is your favorite way to waste time at work?",
        "Have you ever accidentally replied to a rejection email?", "What is the most embarrassing typo you've made?", "Have you ever taken credit for a team effort?", "What is the most micromanaging thing a boss has done?", "Have you ever cried in the office bathroom?",
        "What is the most ridiculous dress code rule you've had to follow?", "Have you ever eaten someone else's food from the fridge?", "What is the most awkward holiday party moment?", "Have you ever lied about your salary to a coworker?", "What is your favorite way to procrastinate?",
        "Have you ever accidentally left a meeting early?", "What is the most unhelpful feedback you've received?", "Have you ever secretly worked a second job during company time?", "What is the most unprofessional thing you've seen a boss do?", "Have you ever lied during a performance review?"
    ]

    office_d = [
        "Do your best impression of your manager.", "Send a friendly but slightly weird email to a colleague now.", "Spend the next round talking like you are in a job interview.", "Re-enact your most awkward work moment.", "Give a motivational speech like a CEO for 30 seconds.",
        "Do 10 desk push-ups.", "Reply to the next question with only corporate buzzwords.", "Describe your job using only emojis.", "Write a haiku about your daily commute.", "Pitch a ridiculous product idea to the group.",
        "Pretend to fire someone in the room.", "Act out a typical Monday morning.", "Send a slack/teams message to your team saying 'I am the captain now.'", "Speak in a customer service voice for the next 2 rounds.", "Show the group your most recent work email.",
        "Pretend you are presenting a graph showing terrible sales.", "Give a completely fake status update on a project.", "Act like you are trying to unjam the printer.", "Use the phrase 'synergy' in every sentence for the next round.", "Pretend to take an important call and shush everyone.",
        "Let someone organize your desk (or digital desktop).", "Draft an email resigning from your job (don't send it).", "Act like you are running late for a meeting.", "Sing a song about the office coffee.", "Pretend to negotiate a massive pay raise.",
        "Describe your worst coworker without using names.", "Act out being caught sleeping at your desk.", "Use a whiteboard (or paper) to draw your career path.", "Speak only in acronyms for the next round.", "Give an enthusiastic review of a boring office supply.",
        "Pretend you are the IT guy fixing a computer.", "Write a LinkedIn post about a completely mundane achievement.", "Act out a painfully long elevator ride with the boss.", "Give a toast at a fake office holiday party.", "Pretend to struggle with a mute button on a video call.",
        "Use 'circle back' and 'touch base' in your next 3 sentences.", "Describe your dream job in an exaggerated accent.", "Act out how you react when the network goes down.", "Pretend to sell a pen to the person next to you.", "Give a dramatic reading of the company mission statement.",
        "Act like a stressed-out intern.", "Pretend to drop a massive stack of papers.", "Describe your boss using only positive adjectives.", "Act out trying to sneak out of the office early.", "Pretend to lead a wellness seminar for the office.",
        "Give a presentation with an invisible clicker.", "Act like you just realized you missed a major deadline.", "Pretend to organize a team-building exercise.", "Write a sticky note with a cryptic message and hide it.", "Describe a work task as if it were an epic battle.",
        "Pretend to be on a conference call with bad reception.", "Write a fake out-of-office auto-reply.", "Act like you are desperately trying to stay awake in a meeting.", "Give a tutorial on how to use a stapler.", "Pretend to be the office gossip spreading a rumor.",
        "Use 'bandwidth' and 'pivot' in your next sentence.", "Act out a dramatic resignation.", "Write a strongly worded email complaining about the thermostat.", "Pretend to be presenting a quarterly review.", "Give a 30-second elevator pitch for yourself.",
        "Pretend to accidentally share your screen with something embarrassing on it.", "Act like you are carrying a ridiculously heavy box of files.", "Write a review of the office breakroom.", "Pretend to be leading a brainstorming session.", "Give a motivational quote in a robot voice.",
        "Pretend to be stuck in traffic on your commute.", "Act like you are trying to read a tiny font on a screen.", "Write a fake agenda for a 3-hour meeting.", "Pretend to be arguing with a vending machine.", "Give a tour of your imaginary office.",
        "Pretend to be frantically searching for a lost document.", "Act like you are trying to ignore a talkative coworker.", "Write a list of 5 rules for the office kitchen.", "Pretend to be giving a very boring presentation.", "Give a pep talk to your computer.",
        "Pretend to be drinking your 5th cup of coffee.", "Act like you are trying to sneak a snack during a meeting.", "Write a fake memo about a new office policy.", "Pretend to be dealing with a difficult client.", "Give a review of the office chair.",
        "Pretend to be frantically typing an email right before a deadline.", "Act like you are trying to find the mute button on a call.", "Write a fake job description for your role.", "Pretend to be taking a 'mental health break' at your desk.", "Give a 10-second summary of your career."
    ]

    data["popular"] = {"truths": pop_t[:100], "dares": pop_d[:100]}
    data["xtreme"] = {"truths": xtreme_t[:100], "dares": xtreme_d[:100]}
    data["couple"] = {"truths": couple_t[:100], "dares": couple_d[:100]}
    data["spicy"] = {"truths": spicy_t[:100], "dares": spicy_d[:100]}
    data["kids"] = {"truths": kids_t[:100], "dares": kids_d[:100]}
    data["office"] = {"truths": office_t[:100], "dares": office_d[:100]}

    with open("data.json", "w") as f:
        json.dump(data, f, indent=2)

if __name__ == "__main__":
    generate()
